<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <AssemblyName>Cinnamon</AssemblyName>
    <RootNamespace>Cinnamon</RootNamespace>
    <LangVersion>9</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <UCHfolder Condition="'$(UCHfolder)' == ''">D:\Program Files\Steam\steamapps\common\Ultimate Chicken Horse\</UCHfolder>
    <OutputPath>plugins\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx" Private="false">
      <HintPath>$(UCHfolder)BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine" Private="false">
      <HintPath>$(UCHfolder)UltimateChickenHorse_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule" Private="false">
      <HintPath>$(UCHfolder)UltimateChickenHorse_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule" Private="false">
      <HintPath>$(UCHfolder)UltimateChickenHorse_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule" Private="false">
      <HintPath>$(UCHfolder)UltimateChickenHorse_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule" Private="false">
      <HintPath>$(UCHfolder)UltimateChickenHorse_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>

    <Reference Include="Assembly-CSharp" Private="false">
      <HintPath>$(UCHfolder)UltimateChickenHorse_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="com.unity.multiplayer-hlapi.Runtime" Private="false">
      <HintPath>$(UCHfolder)UltimateChickenHorse_Data\Managed\com.unity.multiplayer-hlapi.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="netstandard" Private="false">
      <HintPath>$(UCHfolder)UltimateChickenHorse_Data\Managed\netstandard.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony" Private="false">
      <HintPath>$(UCHfolder)BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
